require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/*_schema.rb'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 150
  AllowURI: true
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/WordArray:
  Enabled: false
