version: "3"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/fulltext
      - bundle_volume:/usr/local/bundle
    ports:
      - "3006:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      MYSQL_PASSWORD: password
  db:
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  bundle_volume:
  mysql_volume:
